workflows:
  movieku-codemagic-branch:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    scripts:
      - bash ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/**/outputs/**/*.apk
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: "reza-codemagic"
          include: true
          source: true
      cancel_previous_builds: false
    publishing:
      email:
        recipients:
          - xsamrez08@gmail.com
    environment:
      groups:
        - staging
      vars:
        PACKAGE_NAME: "com.gibax.movieku"
#      java: 17
